- Fixed grammar, phrasing, and Title Case mistakes in en_us.json
rdvdev2/TimeTravelMod pull request #72
Opened 2020-02-12 12:46 UTC by benserwa

2020-02-12 16:09 UTC, naritanara requested changes
Thank's for your help with the English translation! I marked some things that I would prefer to change before merging.

2020-02-12 16:09 UTC, rdvdev2 commented on src/main/resources/assets/timetravelmod/lang/en_us.json
> +    "gui.tmengineerbook.tmsintroduction": "To travel to other Time Lines you will need a Time Machine. A Time Machine is a multi-block structure made with four different blocks: basic blocks (the str
> although Time Machine Upgrades can optionally replace any basic blocks in the structure

TM upgrades always replace basic blocks, this line is a little bit missleading

2020-02-12 16:10 UTC, naritanara requested changes

2020-02-12 16:10 UTC, rdvdev2 commented on src/main/resources/assets/timetravelmod/lang/en_us.json
> +    "tm.timetravelmod.tier1.description": "A very simple Time Machine. You can only visit the Old West.",
Why is this changed? I personally prefer the original one.

2020-02-13 09:47 UTC, benserwa commented
Found some more stuff and will work on these. Can I recommend that "your Time Line" be changed to "the Present"? I think that's a more intuitively explanatory term to use there.

2020-02-13 09:50 UTC, benserwa commented
I also want to change the temporal error death message to something cooler but it's a matter of taste. I wanted to do the Chrono Trigger reference with "But %s's future refused to change..." but I'm not sure that gets the point across.

2020-02-13 10:34 UTC, benserwa commented
I was a little confused about the meaning of the "tmsintroduction" instructions. Is it accurate now?

2020-02-15 12:47 UTC, naritanara approved these changes
Looks good to me!

2020-02-15 12:49 UTC, merged

2020-02-15 12:50 UTC, rdvdev2 commented
> Found some more stuff and will work on these. Can I recommend that "your Time Line" be changed to "the Present"? I think that's a more intuitively explanatory term to use there.

Make a PR with this, as I don't understand quite well what do you mean.

2020-02-15 12:52 UTC, rdvdev2 commented
> I also want to change the temporal error death message to something cooler but it's a matter of taste. I wanted to do the Chrono Trigger reference with "But %s's future refused to change..." but I'm not sure that gets the point across.

Make a PR too and I will check.